show databases;
create database guro;
show databases;

use guro;
show tables;
select * from member;
select * from cart;
select * from orders;
select * from product;
select * from notice;
select * from feed_back;
select * from consumption_info;

insert into member values (null, "admin@admin.com", "guro", "admin", "010-0000-0000", "관리자", "admin");

INSERT INTO notice(id, date, email, text, title) VALUES (1, "2023-02-10", "admin@admin.com", "🎉축하드립니다!🎉\n\n1월의 베스트 리뷰 당첨자는 'winterberry'님의 '코키티와 함께하는 따뜻한 겨울' 리뷰입니다.👏👏\n🎁상품 발송은 3일 내로 이루어질 예정입니다.🎁", "1월 베스트 리뷰 이벤트 당첨자 발표");
INSERT INTO notice(id, date, email, text, title) VALUES (2, "2023-02-25", "admin@admin.com", "📋안내드립니다.📋\n한정 메뉴 '벵쇼'는 재고 소진을 기해 단종될 예정입니다.😪\n벵쇼를 맛볼 마지막 기회를 놓치지 마시고, 매장을 방문해주세요!🍷", "단종 메뉴 안내");
INSERT INTO notice(id, date, email, text, title) VALUES (3, "2023-03-03", "admin@admin.com", "🌺 코키티 신메뉴 네이밍 이벤트! 🌺\n\n안녕하세요, 코키티 팸 여러분! 🍵✨\n새롭게 선보일 'Rose Garden Tea'의 시그니처 신메뉴가 공개되었습니다! 🌹🐉\n이번에는 Dragon Fruit & Rose flavor의 환상적인 조합을 만나볼 수 있어요! 💖\n\n이 특별한 맛에 어울리는 이름을 여러분의 창의력으로 지어주세요! 💡✍️\n\n📝 이벤트 참여 방법:\n 1️⃣ 코키티 인스타그램 혹은 페이스북에 로그인합니다.\n 2️⃣ #코키티_신메뉴네이밍 해시태그와 함께 여러분이 생각하는 이름을 댓글로 남겨주세요!\n 3️⃣ 추첨을 통해 선정된 이름을 사용하게 되며, 당첨자에게는 특별한 선물을 드립니다! 🎁\n\n📅 이벤트 기간: 2023년 3월 5일 ~ 3월 15일\n🎉 당첨자 발표: 2023년 3월 20일\n\n💡 네이밍 팁:\n\nRose 🌹와 Dragon Fruit 🐉의 특별함을 담아주세요!\n감성적이면서도 기억에 남는 이름을 추천해주세요!\n놀라운 상품과 함께 여러분의 아이디어가 코키티 메뉴에 이름으로 남게 됩니다! ✨\n모든 분들의 참여를 기다립니다! 🎉\n\n코키티 드림. 🍪❤️🍵", "코키티 신메뉴의 이름을 지어주세요");
INSERT INTO notice(id, date, email, text, title) VALUES (4, "2023-03-10", "admin@admin.com", "🎉축하드립니다!🎉\n\n2월의 베스트 리뷰는 'green_tea_fanatic'님의 '코키티의 말차라떼가 다른 곳과 차별화된 이유!' 리뷰입니다.👏👏\n🎁상품 발송은 3일 내로 이루어질 예정입니다.🎁", "2월 베스트 리뷰 이벤트 당첨자 발표");
INSERT INTO notice(id, date, email, text, title) VALUES (5, "2023-04-10", "admin@admin.com", "🎉축하드립니다!🎉\n\n3월 베스트 리뷰 이벤트의 당첨자는 'milktea_lover'님의 '이 가격에 이 퀄리티? 대박!' 리뷰입니다.👏👏\n🎁상품은 다음 주 월요일에 발송됩니다.🎁", "3월 베스트 리뷰 이벤트 당첨자 발표");
INSERT INTO notice(id, date, email, text, title) VALUES (6, "2023-04-25", "admin@admin.com", "🎉코키티 X 현대백화점 팝업스토어 오픈! 🎉\n\n안녕하세요, 코키티 팬 여러분! 💕\n우리가 기다리고 기다리던 코키티의 현대백화점 팝업스토어가 드디어 문을 엽니다! 🛍✨\n\n📅 일정: 2023년 5월 15일 ~ 5월 31일\n📍 위치: 현대백화점 1층 중앙로비\n\n🍪 팝업스토어 한정 메뉴!\n1️⃣ 코키티 오리지널 밀크티 🥛+🍪\n2️⃣ 초코칩 카라멜 티 🍫\n3️⃣ 그린티 레몬 쿠키 프라페 🍃+🍋\n\n🎁 특별 프로모션!\n\n처음 100명에게는 한정판 코키티 텀블러 무료 증정! 🥤✨\n팝업스토어에서 20,000원 이상 구매 시, 코키티 마스코트 스티커 팩 증정! 🎁\n팝업스토어는 현대백화점 내에서만 진행되며, 기간 내에 한정된 수량으로 판매되니 서두르세요! 🏃‍♀️💨\n\n📸 인스타그램에 #코키티X현대백화점 해시태그로 사진을 올리면 추첨을 통해 10분께 놀라운 선물이! 🎁📷\n\n기대하셔도 좋아요! 함께 특별한 티타임을 즐기러 오세요! ☕💖\n코키티 드림. 🌸", "코키티 X 현대백화점 팝업스토어 안내");
INSERT INTO notice(id, date, email, text, title) VALUES (7, "2023-05-03", "admin@admin.com", "인스타그램 팔로워 이벤트에 참여해주셔서 감사합니다! \n🎉당첨자는 'choco_latte'님입니다.🎉\n 이메일을 통해 상세 내용을 안내드리겠습니다.", "팝업스토어 인스타그램 이벤트 발표");
INSERT INTO notice(id, date, email, text, title) VALUES (8, "2023-05-10", "admin@admin.com", "🎉축하드립니다!🎉\n\n4월 베스트 리뷰 이벤트의 당첨자는 'sweetcookie123'님의 '코키티의 신제품 '클라우드'에 관한 고찰' 리뷰입니다.👏👏\n🎁상품은 다음 주 월요일에 발송됩니다.🎁", "4월 베스트 리뷰 이벤트 당첨자 발표");

insert into product(category, product_name, price) values ("signature", "블랙 리치", 5000);
insert into product(category, product_name, price) values ("signature", "드래곤과 장미", 5000);
insert into product(category, product_name, price) values ("signature", "나비의 꿈", 5000);
insert into product(category, product_name, price) values ("signature", "조지아 온 마이 마인드", 5000);
insert into product(category, product_name, price) values ("signature", "망고 패션후르츠", 5000);
insert into product(category, product_name, price) values ("signature", "퍼플 러브", 5000);
insert into product(category, product_name, price) values ("signature", "샌프란시스코의 장미", 5000);
insert into product(category, product_name, price) values ("coldcloud", "브라운슈가 콜드브루", 5000);
insert into product(category, product_name, price) values ("coldcloud", "브라운슈가 달고나라떼", 5000);
insert into product(category, product_name, price) values ("coldcloud", "오레오 브라운슈가", 5000);
insert into product(category, product_name, price) values ("coldcloud", "솜사탕 콜드브루", 5000);
insert into product(category, product_name, price) values ("coldcloud", "솜사탕 그린티", 5000);
insert into product(category, product_name, price) values ("iceblended", "용과", 5000);
insert into product(category, product_name, price) values ("iceblended", "리치", 5000);
insert into product(category, product_name, price) values ("iceblended", "망고", 5000);
insert into product(category, product_name, price) values ("iceblended", "아이스망고 패션후르츠", 5000);
insert into product(category, product_name, price) values ("iceblended", "말차", 5000);
insert into product(category, product_name, price) values ("iceblended", "오레오", 5000);
insert into product(category, product_name, price) values ("iceblended", "피나콜라다", 5000);
insert into product(category, product_name, price) values ("iceblended", "스토리베리", 5000);
insert into product(category, product_name, price) values ("iceblended", "타로", 5000);
insert into product(category, product_name, price) values ("kokeefruittea", "청포도 차", 5000);
insert into product(category, product_name, price) values ("kokeefruittea", "허니 자몽 블랙티", 5000);
insert into product(category, product_name, price) values ("kokeefruittea", "오렌지 상그리아", 5000);
insert into product(category, product_name, price) values ("kokeefruittea", "스토리베리 버진 모히토", 5000);
insert into product(category, product_name, price) values ("milktea", "브라운슈가 밀크티", 5000);
insert into product(category, product_name, price) values ("milktea", "클래식 차이티", 5000);
insert into product(category, product_name, price) values ("milktea", "코코넛 밀크티", 5000);
insert into product(category, product_name, price) values ("milktea", "커피 밀크티", 5000);
insert into product(category, product_name, price) values ("milktea", "허니 밀크티", 5000);
insert into product(category, product_name, price) values ("milktea", "하우스 밀크티", 5000);
insert into product(category, product_name, price) values ("milktea", "코키 밀크티", 5000);
insert into product(category, product_name, price) values ("milktea", "말차 라떼", 5000);
insert into product(category, product_name, price) values ("milktea", "오레오 밀크티", 5000);
insert into product(category, product_name, price) values ("milktea", "스트로베리 밀크티", 5000);

insert into consumption_info(productname, lycheeflavor) values ("블랙 리치", 20); 
insert into consumption_info(productname, dragonfruit, foseflavor) values ("드래곤과 장미", 20, 20); 
insert into consumption_info(productname, peach, strawberryflavor, lemonflavor) values ("나비의 꿈", 20, 20, 20);
insert into consumption_info(productname, oolong, peach) values ("조지아 온 마이 마인드", 20, 20);
insert into consumption_info(productname, mango, milk, passionfruitflavor) values ("망고 패션후르츠", 20, 100, 20);
insert into consumption_info(productname, taro, milk, sugar) values ("퍼플 러브", 20, 100, 20);
insert into consumption_info(productname, roseflavor) values ("샌프란시스코의 장미", 20);
insert into consumption_info(productname, bean, brownsugar) values ("브라운슈가 콜드브루", 20, 20);
insert into consumption_info(productname, brownsugar, milk, dalgonafoam) values ("브라운슈가 달고나라떼", 20, 100, 20);
insert into consumption_info(productname, brownsugar, milk, sweetcloud, oreo) values ("오레오 브라운슈가", 20, 100, 20, 20);
insert into consumption_info(productname, bean, milk, sweetcloud) values ("솜사탕 콜드브루", 20, 100, 20);
insert into consumption_info(productname, greentea, sweetcloud, oreo) values ("솜사탕 그린티", 20, 20, 20);
insert into consumption_info(productname, dragonfruit, syrup, cream) values ("용과", 50, 10, 20);
insert into consumption_info(productname, lychee, syrup, cream) values ("리치", 50, 10, 20);
insert into consumption_info(productname, mango, syrup, cream) values ("망고", 50, 10, 20);
insert into consumption_info(productname, mangopassionfruit, syrup, cream) values ("아이스망고 패션후르츠", 50, 10, 20);
insert into consumption_info(productname, matcha, syrup, cream) values ("말차", 50, 10, 20);
insert into consumption_info(productname, oreo, syrup, cream) values ("오레오", 50, 10, 20);
insert into consumption_info(productname, pinacolada, syrup, cream) values ("피나콜라다", 50, 10, 20);
insert into consumption_info(productname, strawberry, syrup, cream) values ("스트로베리", 50, 10, 20);
insert into consumption_info(productname, taro, syrup, cream) values ("타로", 50, 10, 20);
insert into consumption_info(productname, whitegrape, oolong, kiwiflavor) values ("청포도 차", 20, 20, 20);
insert into consumption_info(productname, orangetea, passionfruitjam, grapefruitflavor) values ("허니 자몽 블랙티", 20, 20, 20);
insert into consumption_info(productname, strawberry, mango, peach, lychee) values ("오렌지 상그리아", 10, 10, 10, 10);
insert into consumption_info(productname, blacktealeaf, grapefruitflavor) values ("스트로베리 버진 모히토", 20, 20);
insert into consumption_info(productname, milk, tealeaf, brownsugar) values ("브라운슈가 밀크티", 100, 20, 20);
insert into consumption_info(productname, condensedmilk, tealeaf, sugar) values ("클래식 차이티", 100, 20, 20);
insert into consumption_info(productname, milk, tealeaf, coconut) values ("코코넛 밀크티", 100, 20, 20);
insert into consumption_info(productname, milk, tealeaf, espresso) values ("커피 밀크티", 100, 20, 20);
insert into consumption_info(productname, milk, tealeaf, honey) values ("허니 밀크티", 100, 20, 20);
insert into consumption_info(productname, milk, tealeaf, sugar) values ("하우스 밀크티", 100, 20, 20);
insert into consumption_info(productname, milk, tealeaf, sugar) values ("코키 밀크티", 100, 20, 20);
insert into consumption_info(productname, milk, tealeaf, matcha) values ("말차 라떼", 100, 20, 20);
insert into consumption_info(productname, milk, tealeaf, oreo) values ("오레오 밀크티", 100, 20, 20);
insert into consumption_info(productname, milk, tealeaf, strawberry) values ("스트로베리 밀크티", 100, 20, 20);